---
- hosts: all
  become: true
  roles:
    - { role: docker, when: "'tag_Docker' in group_names" }
    - { role: powerdns, when: "'tag_PowerDNS' in group_names" }
    - { role: common, when: "'tag_Common' in group_names" }
